# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParrainageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filleuil',
            name='Filiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParrainageApp.Filiaire'),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='Filiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParrainageApp.Filiaire'),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='filleuil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParrainageApp.Filleuil'),
        ),
    ]
