# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParrainageApp', '0003_auto_20171106_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrain',
            name='filleuil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParrainageApp.Filleuil'),
        ),
    ]
