# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParrainageApp', '0004_auto_20171106_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrain',
            name='filleuil',
        ),
        migrations.AddField(
            model_name='filleuil',
            name='Parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParrainageApp.Parrain'),
        ),
    ]
