# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParrainageApp', '0005_auto_20171107_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filleuil',
            name='Parrain',
        ),
        migrations.AddField(
            model_name='parrain',
            name='filleul',
            field=models.ManyToManyField(blank=True, null=True, to='ParrainageApp.Filleuil'),
        ),
    ]
