# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParrainageApp', '0006_auto_20171108_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrain',
            name='filleul',
            field=models.ManyToManyField(blank=True, to='ParrainageApp.Filleuil'),
        ),
    ]
