# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParrainageApp', '0007_auto_20171108_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='filleuil',
            name='sexe',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parrain',
            name='sexe',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='filleuil',
            name='photo',
            field=models.ImageField(blank=True, default='ParrainageApp/static/ParrainageApp/img/PEGGY.jpg', null=True, upload_to='ParrainageApp/static/ParrainageApp/img/'),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='photo',
            field=models.ImageField(blank=True, default='ParrainageApp/static/ParrainageApp/img/PEGGY.jpg', null=True, upload_to='ParrainageApp/static/ParrainageApp/img/'),
        ),
    ]
